modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="modpiolo"
version="1.0.0"
displayName="Mod piolo"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lizar, MCreator"

[[dependencies.modpiolo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



